<a href="https://colab.research.google.com/github/gudellidilipkumar/python/blob/main/Week2_3wed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task
Analyze student test performance by creating matrices for original scores and bonus marks, calculating final scores with bonuses, applying a penalty for late submissions, and transposing the final scores matrix for analysis.

## Create original score matrix

### Subtask:
Define a 3x3 matrix representing the original scores of students in different subjects.


**Reasoning**:
Define a 3x3 NumPy array representing the original scores with sample integer values.



In [1]:
import numpy as np

original_scores = np.array([[85, 78, 92],
                            [65, 70, 88],
                            [90, 85, 75]])
print(original_scores)

[[85 78 92]
 [65 70 88]
 [90 85 75]]


## Design bonus marks matrix

### Subtask:
Create a 3x3 matrix for bonus marks awarded to students in each subject.


**Reasoning**:
Create a 3x3 NumPy array for bonus marks and print it.



In [2]:
bonus_marks = np.array([[5, 3, 2],
                        [2, 4, 1],
                        [3, 1, 5]])
print(bonus_marks)

[[5 3 2]
 [2 4 1]
 [3 1 5]]


## Calculate final scores with bonuses

### Subtask:
Add the bonus matrix to the original scores matrix to get the scores after adding bonuses.


**Reasoning**:
Add the two matrices together and store the result in a new variable, then print the result.



In [3]:
scores_with_bonuses = original_scores + bonus_marks
print(scores_with_bonuses)

[[90 81 94]
 [67 74 89]
 [93 86 80]]


## Apply penalty for late submissions

### Subtask:
Multiply the final scores matrix by a penalty factor to adjust scores due to late submissions.


**Reasoning**:
Define the penalty factor, multiply the scores with bonuses by this factor, store the result, and print it.



In [4]:
penalty_factor = 0.9
penalized_scores = scores_with_bonuses * penalty_factor
print(penalized_scores)

[[81.  72.9 84.6]
 [60.3 66.6 80.1]
 [83.7 77.4 72. ]]


## Transpose the final scores matrix

### Subtask:
Transpose the final scores matrix to easily analyze performance by subject and student.


**Reasoning**:
Transpose the penalized scores matrix and print the result.



In [5]:
transposed_scores = penalized_scores.T
print(transposed_scores)

[[81.  60.3 83.7]
 [72.9 66.6 77.4]
 [84.6 80.1 72. ]]


## Display results

### Subtask:
Print the original scores, bonus marks, scores with bonuses, penalized scores, and transposed penalized scores.


**Reasoning**:
Print all the matrices with descriptive labels as requested.



In [6]:
print("Original Scores:")
print(original_scores)
print("\nBonus Marks:")
print(bonus_marks)
print("\nScores with Bonuses:")
print(scores_with_bonuses)
print("\nPenalized Scores:")
print(penalized_scores)
print("\nTransposed Penalized Scores:")
print(transposed_scores)

Original Scores:
[[85 78 92]
 [65 70 88]
 [90 85 75]]

Bonus Marks:
[[5 3 2]
 [2 4 1]
 [3 1 5]]

Scores with Bonuses:
[[90 81 94]
 [67 74 89]
 [93 86 80]]

Penalized Scores:
[[81.  72.9 84.6]
 [60.3 66.6 80.1]
 [83.7 77.4 72. ]]

Transposed Penalized Scores:
[[81.  60.3 83.7]
 [72.9 66.6 77.4]
 [84.6 80.1 72. ]]


## Summary:

### Data Analysis Key Findings

*   The original scores matrix was successfully created, representing initial student performance.
*   A bonus marks matrix was added to the original scores, increasing student scores.
*   A penalty factor of 0.9 was applied to the scores with bonuses, resulting in a decrease in scores due to late submissions.
*   The final penalized scores matrix was transposed, allowing for analysis by subject and student.

### Insights or Next Steps

*   The transposed matrix facilitates comparison of student performance across subjects and identification of subject-specific trends.
*   Further analysis could involve calculating average scores per student or subject from the transposed matrix.


## Interpret the Results

### Subtask:
Interpret the results from the transposed matrix to identify the subject with the highest average score and the student who improved the most due to bonus marks.

**Reasoning**:
Calculate the average score for each subject from the transposed penalized scores matrix to identify the subject with the highest average. Also, compare the original scores to the scores with bonuses for each student to determine who improved the most.

In [7]:
# Calculate average score per subject from the transposed penalized scores matrix
average_scores_per_subject = np.mean(transposed_scores, axis=1)

# Identify the subject with the highest average score
subjects = ["Mathematics", "Science", "English"]
highest_average_subject_index = np.argmax(average_scores_per_subject)
highest_average_subject = subjects[highest_average_subject_index]
highest_average_score = average_scores_per_subject[highest_average_subject_index]

print(f"Average scores per subject: {average_scores_per_subject}")
print(f"Subject with the highest average score: {highest_average_subject} ({highest_average_score:.2f})")

# Calculate improvement for each student due to bonus marks
improvement_due_to_bonuses = scores_with_bonuses - original_scores

# Sum the improvement across all subjects for each student
total_improvement_per_student = np.sum(improvement_due_to_bonuses, axis=1)

# Identify the student who improved the most
students = ["Student 1", "Student 2", "Student 3"]
most_improved_student_index = np.argmax(total_improvement_per_student)
most_improved_student = students[most_improved_student_index]
highest_improvement = total_improvement_per_student[most_improved_student_index]

print(f"\nTotal improvement per student due to bonus marks: {total_improvement_per_student}")
print(f"Student who improved the most due to bonus marks: {most_improved_student} (Total improvement: {highest_improvement})")

Average scores per subject: [75.  72.3 78.9]
Subject with the highest average score: English (78.90)

Total improvement per student due to bonus marks: [10  7  9]
Student who improved the most due to bonus marks: Student 1 (Total improvement: 10)
